'use client';

import type { FormEvent, ReactNode } from 'react';
import { useMemo, useState } from 'react';
import {
  AlertTriangle, ArrowDownLeft, ArrowUpRight, BadgeCheck, Banknote, Bell, Bolt,
  BriefcaseBusiness, CalendarCheck2, CalendarDays, Check, CheckCheck, CheckCircle2,
  ChevronDown, CircleDollarSign, Clock3, Download, FileText, Filter, LayoutDashboard,
  Mail, MapPin, Menu, MessageSquareText, MoreHorizontal, Paperclip, Plus, ReceiptText,
  Search, Send, ShieldCheck, Sparkles, Star, TrendingUp, UserCheck, UserPlus, Users,
  WalletCards, X,
} from 'lucide-react';

type ViewName = 'Resumen' | 'Turnos' | 'Trabajadores' | 'Mensajes' | 'Pagos';
type Coverage = 'Completo' | 'Falta 1' | 'En selección';
type Shift = { id: number; role: string; date: string; schedule: string; location: string; confirmed: number; required: number; pay: number; coverage: Coverage };
type Worker = { id: number; initials: string; name: string; role: string; match: number; score: number; available: string; status: 'Disponible' | 'En turno' | 'No disponible'; jobs: number; skills: string[] };
type Conversation = { id: number; initials: string; name: string; role: string; preview: string; time: string; unread: number; online: boolean };
type ChatMessage = { id: number; sender: 'company' | 'worker'; text: string; time: string };
type Transaction = { id: string; description: string; date: string; workers: number; amount: number; status: 'Procesado' | 'Pendiente' | 'Programado' };

const navigation: { label: ViewName; icon: typeof LayoutDashboard; badge?: string }[] = [
  { label: 'Resumen', icon: LayoutDashboard }, { label: 'Turnos', icon: CalendarDays, badge: '8' },
  { label: 'Trabajadores', icon: Users }, { label: 'Mensajes', icon: MessageSquareText, badge: '3' },
  { label: 'Pagos', icon: CircleDollarSign },
];

const initialShifts: Shift[] = [
  { id: 1, role: 'Mozo de salón', date: 'Hoy, 22 ago', schedule: '18:00 – 00:00', location: 'Miraflores', confirmed: 3, required: 4, pay: 100, coverage: 'Falta 1' },
  { id: 2, role: 'Ayudante de cocina', date: 'Hoy, 22 ago', schedule: '10:00 – 18:00', location: 'San Isidro', confirmed: 3, required: 3, pay: 120, coverage: 'Completo' },
  { id: 3, role: 'Anfitrión de eventos', date: 'Mañana, 23 ago', schedule: '16:00 – 22:00', location: 'Barranco', confirmed: 4, required: 5, pay: 95, coverage: 'En selección' },
  { id: 4, role: 'Bartender de refuerzo', date: 'Mañana, 23 ago', schedule: '19:00 – 03:00', location: 'Miraflores', confirmed: 2, required: 2, pay: 110, coverage: 'Completo' },
  { id: 5, role: 'Personal de limpieza', date: 'Lun, 25 ago', schedule: '06:00 – 12:00', location: 'San Isidro', confirmed: 1, required: 2, pay: 85, coverage: 'En selección' },
];

const workers: Worker[] = [
  { id: 1, initials: 'AM', name: 'Ana Mendoza', role: 'Servicio y eventos', match: 98, score: 96, available: 'Disponible ahora', status: 'Disponible', jobs: 42, skills: ['Servicio', 'Eventos'] },
  { id: 2, initials: 'CR', name: 'Carlos Rojas', role: 'Cocina y producción', match: 94, score: 92, available: 'Disponible desde 17:00', status: 'Disponible', jobs: 31, skills: ['Cocina', 'Producción'] },
  { id: 3, initials: 'LV', name: 'Lucía Vargas', role: 'Bar y atención', match: 91, score: 95, available: 'En turno hasta 16:00', status: 'En turno', jobs: 38, skills: ['Bar', 'Atención'] },
  { id: 4, initials: 'JP', name: 'José Paredes', role: 'Logística y almacén', match: 89, score: 90, available: 'Disponible mañana', status: 'No disponible', jobs: 26, skills: ['Logística', 'Inventario'] },
  { id: 5, initials: 'SF', name: 'Sofía Flores', role: 'Anfitriona y caja', match: 93, score: 97, available: 'Disponible ahora', status: 'Disponible', jobs: 47, skills: ['Caja', 'Anfitriona'] },
  { id: 6, initials: 'DM', name: 'Diego Molina', role: 'Limpieza y apoyo', match: 87, score: 91, available: 'Disponible desde 14:00', status: 'Disponible', jobs: 22, skills: ['Limpieza', 'Apoyo'] },
];

const conversations: Conversation[] = [
  { id: 1, initials: 'CR', name: 'Carlos Rojas', role: 'Ayudante de cocina', preview: '¿El uniforme incluye mandil?', time: '10:42', unread: 2, online: true },
  { id: 2, initials: 'AM', name: 'Ana Mendoza', role: 'Mozo de salón', preview: 'Perfecto, estaré 15 min antes.', time: '09:18', unread: 0, online: true },
  { id: 3, initials: 'SF', name: 'Sofía Flores', role: 'Anfitriona', preview: 'Gracias por la confirmación.', time: 'Ayer', unread: 1, online: false },
  { id: 4, initials: 'LV', name: 'Lucía Vargas', role: 'Bartender', preview: 'Adjunto mi certificado actualizado.', time: 'Ayer', unread: 0, online: false },
];

const initialMessages: Record<number, ChatMessage[]> = {
  1: [{ id: 1, sender: 'company', text: 'Hola Carlos, tu ingreso está confirmado para hoy a las 10:00.', time: '10:34' }, { id: 2, sender: 'worker', text: '¡Gracias! Ya revisé la ubicación. ¿El uniforme incluye mandil?', time: '10:42' }],
  2: [{ id: 3, sender: 'company', text: 'Hola Ana, recuerda ingresar por la puerta de personal.', time: '09:12' }, { id: 4, sender: 'worker', text: 'Perfecto, estaré 15 min antes.', time: '09:18' }],
  3: [{ id: 5, sender: 'worker', text: 'Gracias por la confirmación. Nos vemos mañana.', time: '18:05' }],
  4: [{ id: 6, sender: 'worker', text: 'Adjunto mi certificado actualizado.', time: '16:20' }],
};

const transactions: Transaction[] = [
  { id: 'CN-0822', description: 'Turnos validados · 18–22 ago', date: '22 ago 2026', workers: 8, amount: 920, status: 'Procesado' },
  { id: 'CN-0828', description: 'Próximo desembolso', date: '28 ago 2026', workers: 15, amount: 1840, status: 'Programado' },
  { id: 'CN-0815', description: 'Turnos validados · 11–15 ago', date: '15 ago 2026', workers: 12, amount: 1480, status: 'Procesado' },
  { id: 'CN-0823', description: 'Validación pendiente · evento', date: '23 ago 2026', workers: 4, amount: 380, status: 'Pendiente' },
];

const activity = [
  { icon: UserCheck, title: 'Ana confirmó el turno', detail: 'Mozo de salón · hace 8 min', tone: 'teal' },
  { icon: MessageSquareText, title: 'Nuevo mensaje de Carlos', detail: 'Consulta sobre uniforme · hace 24 min', tone: 'navy' },
  { icon: ReceiptText, title: 'Pago de turno liberado', detail: 'S/ 360 · hace 1 h', tone: 'gold' },
];

function coverageClass(coverage: Coverage) {
  if (coverage === 'Completo') return 'complete';
  if (coverage === 'Falta 1') return 'urgent';
  return '';
}

export default function HomePage() {
  const [activeNav, setActiveNav] = useState<ViewName>('Resumen');
  const [mobileMenu, setMobileMenu] = useState(false);
  const [publishOpen, setPublishOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [shiftFilter, setShiftFilter] = useState<'Todos' | 'Por cubrir' | 'Completos'>('Todos');
  const [period, setPeriod] = useState('Esta semana');
  const [rescueActive, setRescueActive] = useState(false);
  const [shifts, setShifts] = useState(initialShifts);
  const [shiftSearch, setShiftSearch] = useState('');
  const [selectedShiftId, setSelectedShiftId] = useState(1);
  const [workerSearch, setWorkerSearch] = useState('');
  const [workerFilter, setWorkerFilter] = useState<'Todos' | 'Disponibles' | 'En turno'>('Todos');
  const [selectedConversation, setSelectedConversation] = useState(1);
  const [messageSearch, setMessageSearch] = useState('');
  const [chatMessages, setChatMessages] = useState(initialMessages);
  const [paymentFilter, setPaymentFilter] = useState<'Todos' | 'Procesados' | 'Pendientes'>('Todos');
  const [toast, setToast] = useState<string | null>(null);

  const filteredShifts = useMemo(() => shifts.filter((shift) => {
    const matchesStatus = shiftFilter === 'Todos' || (shiftFilter === 'Por cubrir' ? shift.coverage !== 'Completo' : shift.coverage === 'Completo');
    const query = shiftSearch.trim().toLowerCase();
    return matchesStatus && (!query || `${shift.role} ${shift.location} ${shift.date}`.toLowerCase().includes(query));
  }), [shiftFilter, shiftSearch, shifts]);
  const filteredWorkers = useMemo(() => workers.filter((worker) => {
    const matchesStatus = workerFilter === 'Todos' || (workerFilter === 'Disponibles' ? worker.status === 'Disponible' : worker.status === 'En turno');
    const query = workerSearch.trim().toLowerCase();
    return matchesStatus && (!query || `${worker.name} ${worker.role} ${worker.skills.join(' ')}`.toLowerCase().includes(query));
  }), [workerFilter, workerSearch]);
  const filteredConversations = conversations.filter((item) => `${item.name} ${item.role}`.toLowerCase().includes(messageSearch.trim().toLowerCase()));
  const selectedConversationData = conversations.find((item) => item.id === selectedConversation) ?? conversations[0];
  const selectedShift = shifts.find((shift) => shift.id === selectedShiftId) ?? shifts[0];
  const filteredTransactions = transactions.filter((item) => paymentFilter === 'Todos' || (paymentFilter === 'Procesados' ? item.status === 'Procesado' : item.status !== 'Procesado'));

  function navigate(label: ViewName) { setActiveNav(label); setMobileMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function showToast(message: string) { setToast(message); window.setTimeout(() => setToast(null), 3200); }
  function publishShift(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const newShift: Shift = { id: Date.now(), role: String(data.get('role') || 'Nuevo turno'), date: 'Próximo turno', schedule: String(data.get('schedule')), location: String(data.get('location')), confirmed: 0, required: Number(data.get('required') || 1), pay: Number(data.get('pay') || 100), coverage: 'En selección' };
    setShifts((current) => [newShift, ...current]); setSelectedShiftId(newShift.id); setPublishOpen(false); setShiftFilter('Todos'); navigate('Turnos'); showToast('Turno publicado. Ya estamos buscando perfiles compatibles.');
  }
  function sendMessage(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const text = String(new FormData(form).get('message') || '').trim(); if (!text) return;
    setChatMessages((current) => ({ ...current, [selectedConversation]: [...(current[selectedConversation] ?? []), { id: Date.now(), sender: 'company', text, time: 'Ahora' }] })); form.reset();
  }

  return (
    <div className="app-shell">
      {mobileMenu && <button className="page-scrim" aria-label="Cerrar menú" onClick={() => setMobileMenu(false)} />}
      <aside className={`sidebar${mobileMenu ? ' open' : ''}`} aria-label="Navegación principal">
        <div className="brand"><div className="brand-mark">CN</div><div><div className="brand-name">CUMPLE <span>NOW</span></div><div className="brand-caption">Panel para empresas</div></div><button className="sidebar-close" aria-label="Cerrar menú" onClick={() => setMobileMenu(false)}><X size={19} /></button></div>
        <div className="nav-label">Operaciones</div>
        <nav className="nav">{navigation.map(({ label, icon: Icon, badge }) => <button className={`nav-item${activeNav === label ? ' active' : ''}`} aria-current={activeNav === label ? 'page' : undefined} key={label} type="button" onClick={() => navigate(label)}><Icon size={18} /><span>{label}</span>{badge && <span className="nav-badge">{badge}</span>}</button>)}</nav>
        <div className="sidebar-spacer" /><div className="support-card"><Sparkles size={17} /><div><strong>¿Necesitas ayuda?</strong><span>Habla con soporte</span></div><ArrowUpRight size={15} /></div>
        <button className="company-card" type="button" onClick={() => showToast('Perfil empresarial verificado y al día.')}><span className="company-logo">LM</span><span className="company-copy"><strong>Restaurante La Mar</strong><span>Empresa verificada</span></span><ChevronDown size={16} color="#718096" /></button>
      </aside>

      <main className="main">
        <header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" type="button" aria-label="Abrir menú" onClick={() => setMobileMenu(true)}><Menu size={20} /></button><div className="breadcrumb">Empresa / <strong>{activeNav}</strong></div></div><div className="topbar-actions"><label className="period-control"><span>Periodo</span><select value={period} onChange={(event) => setPeriod(event.target.value)}><option>Esta semana</option><option>Este mes</option><option>Últimos 30 días</option></select></label><button className="icon-button" type="button" aria-label="Ver notificaciones" onClick={() => setNotificationsOpen(true)}><Bell size={18} /><span className="notification-dot" /></button><button className="secondary-button" type="button" onClick={() => navigate('Trabajadores')}><Users size={17} /> Equipo</button><button className="primary-button" type="button" onClick={() => setPublishOpen(true)}><Plus size={18} /><span>Publicar turno</span></button></div></header>

        {activeNav === 'Resumen' && <Overview shifts={shifts} period={period} rescueActive={rescueActive} onRescue={() => { setRescueActive(true); showToast('Rescate activado. Te avisaremos cuando un perfil confirme.'); }} onNavigate={navigate} onShift={(id) => { setSelectedShiftId(id); navigate('Turnos'); }} onToast={showToast} />}

        {activeNav === 'Turnos' && <div className="workspace view-workspace">
          <ViewHeader eyebrow="Planificación operativa" title="Turnos" description="Publica, cubre y supervisa tus necesidades de personal desde un solo lugar."><button className="secondary-button" type="button" onClick={() => showToast('Calendario sincronizado con los turnos actuales.')}><CalendarCheck2 size={17} /> Calendario</button><button className="primary-button" type="button" onClick={() => setPublishOpen(true)}><Plus size={17} /> Nuevo turno</button></ViewHeader>
          <section className="view-stat-grid"><MiniStat label="Publicados" value={String(shifts.length)} detail="3 esta semana" icon={CalendarDays} /><MiniStat label="Por cubrir" value={String(shifts.filter((shift) => shift.coverage !== 'Completo').length)} detail="Requieren atención" icon={AlertTriangle} warning /><MiniStat label="Confirmaciones" value="13/16" detail="81% de cobertura" icon={UserCheck} /><MiniStat label="Costo estimado" value="S/ 1,525" detail="Incluye comisión" icon={CircleDollarSign} /></section>
          <section className="management-grid"><article className="panel management-list"><div className="management-toolbar"><label className="search-control"><Search size={16} /><input aria-label="Buscar turnos" placeholder="Buscar por rol, sede o fecha" value={shiftSearch} onChange={(event) => setShiftSearch(event.target.value)} /></label><div className="filter-tabs">{(['Todos', 'Por cubrir', 'Completos'] as const).map((filter) => <button className={shiftFilter === filter ? 'active' : ''} key={filter} type="button" onClick={() => setShiftFilter(filter)}>{filter}</button>)}</div><button className="compact-button" type="button" onClick={() => showToast('Filtros ordenados por fecha más próxima.')}><Filter size={15} /> Más filtros</button></div><div className="managed-shifts">{filteredShifts.map((shift) => <ManagedShift key={shift.id} shift={shift} selected={selectedShift?.id === shift.id} onSelect={() => setSelectedShiftId(shift.id)} />)}{filteredShifts.length === 0 && <div className="empty-state"><Search size={24} /><strong>No encontramos turnos</strong><span>Ajusta la búsqueda o cambia el filtro.</span></div>}</div></article>
            {selectedShift && <aside className="panel detail-panel"><div className="detail-top"><span className={`coverage-badge ${coverageClass(selectedShift.coverage)}`}>{selectedShift.coverage}</span><button className="row-action" type="button" aria-label="Más acciones" onClick={() => showToast('Menú de acciones del turno abierto.')}><MoreHorizontal size={18} /></button></div><div className="detail-icon"><BriefcaseBusiness size={22} /></div><p className="eyebrow">Detalle del turno</p><h2>{selectedShift.role}</h2><div className="detail-facts"><span><CalendarDays size={16} /><i><small>Fecha</small><strong>{selectedShift.date}</strong></i></span><span><Clock3 size={16} /><i><small>Horario</small><strong>{selectedShift.schedule}</strong></i></span><span><MapPin size={16} /><i><small>Sede</small><strong>{selectedShift.location}</strong></i></span></div><div className="detail-progress"><div><span>Cobertura</span><strong>{selectedShift.confirmed} de {selectedShift.required}</strong></div><div className="progress-track"><div style={{ width: `${Math.round(selectedShift.confirmed / selectedShift.required * 100)}%` }} /></div></div><div className="detail-cost"><span>Inversión estimada</span><strong>S/ {selectedShift.pay * selectedShift.required}</strong><small>S/ {selectedShift.pay} por persona</small></div><button className="primary-button full-action" type="button" onClick={() => { setRescueActive(true); showToast(`Búsqueda prioritaria activada para ${selectedShift.role}.`); }}><Bolt size={17} /> {selectedShift.coverage === 'Completo' ? 'Ver equipo asignado' : 'Acelerar cobertura'}</button><button className="secondary-button full-action" type="button" onClick={() => showToast('Edición del turno habilitada.')}><FileText size={16} /> Editar información</button></aside>}
          </section>
        </div>}

        {activeNav === 'Trabajadores' && <div className="workspace view-workspace">
          <ViewHeader eyebrow="Red de talento" title="Trabajadores" description="Encuentra perfiles verificados, revisa su desempeño y forma tu equipo frecuente."><button className="secondary-button" type="button" onClick={() => showToast('Invitación privada lista para compartir.')}><Mail size={17} /> Invitar por enlace</button><button className="primary-button" type="button" onClick={() => showToast('Buscando talento para tus próximos turnos.')}><UserPlus size={17} /> Buscar talento</button></ViewHeader>
          <section className="talent-summary"><article className="talent-highlight"><span className="talent-highlight-icon"><BadgeCheck size={23} /></span><div><p>Equipo frecuente</p><strong>18 trabajadores</strong><small>94% de asistencia promedio</small></div><div className="talent-avatars">{workers.slice(0, 4).map((worker) => <i key={worker.id}>{worker.initials}</i>)}</div></article><MiniStat label="Disponibles hoy" value="12" detail="4 cerca de tus sedes" icon={UserCheck} /><MiniStat label="Índice promedio" value="94" detail="Nivel excelente" icon={Star} /></section>
          <section className="panel directory-panel"><div className="directory-header"><div><h2>Directorio de talento</h2><p>Perfiles sugeridos según tu historial y necesidades activas.</p></div><span className="ai-chip"><Sparkles size={12} /> Ordenado por compatibilidad</span></div><div className="management-toolbar"><label className="search-control"><Search size={16} /><input aria-label="Buscar trabajadores" placeholder="Buscar por nombre, rol o habilidad" value={workerSearch} onChange={(event) => setWorkerSearch(event.target.value)} /></label><div className="filter-tabs">{(['Todos', 'Disponibles', 'En turno'] as const).map((filter) => <button className={workerFilter === filter ? 'active' : ''} key={filter} type="button" onClick={() => setWorkerFilter(filter)}>{filter}</button>)}</div><button className="compact-button" type="button" onClick={() => showToast('Filtros de habilidades disponibles.')}><Filter size={15} /> Habilidades</button></div>
            <div className="worker-directory">{filteredWorkers.map((worker) => <WorkerDirectoryCard key={worker.id} worker={worker} onMessage={() => { setSelectedConversation(worker.id > 4 ? 1 : worker.id); navigate('Mensajes'); }} onInvite={() => showToast(`Invitación enviada a ${worker.name}.`)} />)}{filteredWorkers.length === 0 && <div className="empty-state directory-empty"><Search size={24} /><strong>No hay perfiles con estos criterios</strong><span>Prueba con otra habilidad o disponibilidad.</span></div>}</div>
          </section>
        </div>}

        {activeNav === 'Mensajes' && <div className="workspace view-workspace messages-workspace">
          <ViewHeader eyebrow="Comunicación centralizada" title="Mensajes" description="Coordina ingresos, indicaciones y cambios sin salir del panel."><button className="secondary-button" type="button" onClick={() => showToast('Todos los mensajes fueron marcados como leídos.')}><CheckCheck size={17} /> Marcar leídos</button><button className="primary-button" type="button" onClick={() => showToast('Selecciona un trabajador para iniciar una conversación.')}><Plus size={17} /> Nuevo mensaje</button></ViewHeader>
          <section className="messages-shell"><aside className="conversation-panel"><div className="conversation-header"><div><h2>Conversaciones</h2><span>3 sin leer</span></div><label className="search-control"><Search size={15} /><input aria-label="Buscar conversaciones" placeholder="Buscar conversación" value={messageSearch} onChange={(event) => setMessageSearch(event.target.value)} /></label></div><div className="conversation-list">{filteredConversations.map((conversation) => <button className={`conversation-item${selectedConversation === conversation.id ? ' active' : ''}`} type="button" key={conversation.id} onClick={() => setSelectedConversation(conversation.id)}><span className="conversation-avatar">{conversation.initials}{conversation.online && <i />}</span><span className="conversation-copy"><span><strong>{conversation.name}</strong><time>{conversation.time}</time></span><small>{conversation.role}</small><p>{conversation.preview}</p></span>{conversation.unread > 0 && <b>{conversation.unread}</b>}</button>)}{filteredConversations.length === 0 && <div className="empty-state"><Search size={23} /><strong>Sin resultados</strong><span>Busca por nombre o rol.</span></div>}</div></aside>
            <article className="chat-panel"><header className="chat-header"><div className="conversation-avatar large">{selectedConversationData.initials}{selectedConversationData.online && <i />}</div><div><h2>{selectedConversationData.name}</h2><p>{selectedConversationData.online ? 'En línea' : selectedConversationData.role}</p></div><button className="row-action" type="button" aria-label="Más acciones" onClick={() => showToast('Información del trabajador actualizada.')}><MoreHorizontal size={20} /></button></header><div className="shift-context"><CalendarCheck2 size={17} /><span><small>Conversación sobre</small><strong>{selectedConversationData.role} · Hoy, 18:00</strong></span><button type="button" onClick={() => navigate('Turnos')}>Ver turno</button></div><div className="chat-thread"><div className="day-divider"><span>Hoy</span></div>{(chatMessages[selectedConversation] ?? []).map((message) => <div className={`message-bubble ${message.sender}`} key={message.id}><p>{message.text}</p><small>{message.time}{message.sender === 'company' && <CheckCheck size={12} />}</small></div>)}</div><form className="message-composer" onSubmit={sendMessage}><button type="button" aria-label="Adjuntar archivo" onClick={() => showToast('Adjunta documentos o indicaciones para el turno.')}><Paperclip size={18} /></button><input name="message" autoComplete="off" aria-label="Escribir mensaje" placeholder="Escribe una indicación para el trabajador…" /><button className="send-button" type="submit" aria-label="Enviar mensaje"><Send size={17} /></button></form></article>
          </section>
        </div>}

        {activeNav === 'Pagos' && <div className="workspace view-workspace">
          <ViewHeader eyebrow="Control financiero" title="Pagos" description="Supervisa fondos, validaciones y desembolsos de todos tus turnos."><button className="secondary-button" type="button" onClick={() => showToast('Reporte financiero preparado para descarga.')}><Download size={17} /> Exportar</button><button className="primary-button" type="button" onClick={() => showToast('S/ 2,500 agregados al saldo protegido.')}><Plus size={17} /> Agregar fondos</button></ViewHeader>
          <section className="finance-overview"><article className="balance-card"><div className="balance-head"><span>Saldo disponible</span><ShieldCheck size={18} /></div><strong>S/ 4,820.00</strong><p>Fondos protegidos para cubrir tus próximos turnos.</p><div><span><small>Comprometido</small><b>S/ 1,840</b></span><span><small>Disponible</small><b>S/ 2,980</b></span></div></article><MiniStat label="Pagado este mes" value="S/ 7,260" detail="+12% vs. julio" icon={TrendingUp} /><MiniStat label="Por validar" value="S/ 380" detail="4 turnos pendientes" icon={Clock3} warning /><MiniStat label="Comisión de servicio" value="S/ 806" detail="Incluida en el total" icon={ReceiptText} /></section>
          <section className="payment-content-grid"><article className="panel transaction-panel"><div className="directory-header"><div><h2>Movimientos</h2><p>Pagos y desembolsos asociados a tus operaciones.</p></div><button className="compact-button" type="button" onClick={() => showToast('Comprobante consolidado listo.')}><FileText size={15} /> Comprobantes</button></div><div className="management-toolbar payment-toolbar"><div className="filter-tabs">{(['Todos', 'Procesados', 'Pendientes'] as const).map((filter) => <button className={paymentFilter === filter ? 'active' : ''} key={filter} type="button" onClick={() => setPaymentFilter(filter)}>{filter}</button>)}</div><button className="compact-button" type="button"><Filter size={15} /> Fecha</button></div><div className="transaction-table"><div className="transaction-head"><span>Movimiento</span><span>Trabajadores</span><span>Estado</span><span>Monto</span><span /></div>{filteredTransactions.map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} onOpen={() => showToast(`Detalle ${transaction.id} disponible.`)} />)}</div></article>
            <aside className="payment-side"><article className="panel payout-card"><div className="payout-icon"><Banknote size={21} /></div><span>Próximo desembolso</span><strong>S/ 1,840.00</strong><small>Viernes, 28 de agosto</small><div className="payout-step"><span><Check size={13} /></span><div><strong>12 turnos validados</strong><small>Faltan 4 por validar</small></div></div><div className="payment-progress"><i /></div><button className="full-secondary" type="button" onClick={() => showToast('Revisando los 4 turnos pendientes.')}><CheckCircle2 size={16} /> Validar turnos</button></article><article className="panel billing-card"><div><WalletCards size={18} /><span><strong>Método de pago</strong><small>Visa empresarial ···· 4821</small></span></div><button type="button" onClick={() => showToast('Método de pago verificado.')}><ArrowUpRight size={15} /></button></article></aside>
          </section>
        </div>}
      </main>

      {publishOpen && <PublishModal onClose={() => setPublishOpen(false)} onSubmit={publishShift} />}
      {notificationsOpen && <><button className="drawer-scrim" aria-label="Cerrar notificaciones" onClick={() => setNotificationsOpen(false)} /><aside className="notification-drawer" aria-label="Notificaciones"><div className="drawer-header"><div><p className="eyebrow">Centro de alertas</p><h2>Notificaciones</h2></div><button className="icon-button" type="button" aria-label="Cerrar" onClick={() => setNotificationsOpen(false)}><X size={18} /></button></div><div className="notice important"><span><Bolt size={18} /></span><div><strong>Turno con cobertura incompleta</strong><p>Falta una persona para el turno de mozo de salón de las 18:00.</p><button type="button" onClick={() => { setNotificationsOpen(false); setRescueActive(true); navigate('Turnos'); showToast('Rescate activado desde notificaciones.'); }}>Gestionar cobertura</button></div></div><div className="notice"><span><UserCheck size={18} /></span><div><strong>Nueva confirmación</strong><p>Ana Mendoza confirmó asistencia para hoy.</p><small>Hace 8 minutos</small></div></div><div className="notice"><span><Send size={18} /></span><div><strong>3 mensajes sin leer</strong><p>Tu equipo necesita indicaciones para el ingreso.</p><button type="button" onClick={() => { setNotificationsOpen(false); navigate('Mensajes'); }}>Revisar mensajes</button></div></div></aside></>}
      {toast && <div className="toast" role="status" aria-live="polite"><CheckCircle2 size={18} /><span>{toast}</span><button aria-label="Cerrar aviso" onClick={() => setToast(null)}><X size={15} /></button></div>}
    </div>
  );
}

function Overview({ shifts, period, rescueActive, onRescue, onNavigate, onShift, onToast }: { shifts: Shift[]; period: string; rescueActive: boolean; onRescue: () => void; onNavigate: (view: ViewName) => void; onShift: (id: number) => void; onToast: (message: string) => void }) {
  return <div className="workspace"><section className="welcome-row"><div><p className="eyebrow">Centro de operaciones</p><h1>Buenos días, La Mar</h1><p className="welcome-copy">Tu operación está estable. Hay un turno que requiere atención hoy.</p></div><div className="date-chip"><CalendarDays size={15} /> Viernes, 22 de agosto</div></section>
    <section className="metric-grid"><MetricCard label="Turnos activos" value={String(shifts.length + 3)} trend="+2 esta semana" icon={CalendarDays} /><MetricCard label="Cobertura promedio" value="92%" trend="+6%" icon={ShieldCheck} /><MetricCard label="Trabajadores hoy" value="24" trend="21 confirmados" icon={Users} /><MetricCard label="Pago pendiente" value="S/ 1,840" trend="Viernes" icon={CircleDollarSign} gold /></section>
    <section className="priority-grid"><article className="panel"><div className="panel-heading"><div><h2>Turno prioritario de hoy</h2><p>Monitorea la cobertura antes de iniciar la operación.</p></div><span className={rescueActive ? 'status-pill resolved' : 'status-pill'}>{rescueActive ? 'Rescate activo' : 'Requiere 1 persona'}</span></div><div className="shift-feature"><div><div className="shift-title-row"><span className="urgent-dot" /><h3>Mozo de salón · Cena</h3></div><div className="shift-meta"><span><Clock3 size={14} /> 18:00 – 00:00</span><span><MapPin size={14} /> Miraflores</span><span><Star size={14} /> 4.8 mínimo</span></div><div className="coverage"><div className="coverage-copy"><span>Cobertura confirmada</span><strong>3 de 4</strong></div><div className="progress-track"><div className="progress-bar" /></div></div></div><div className="shift-pay"><span>Pago por persona</span><strong>S/ 100</strong><small>6 horas</small></div></div></article><article className={`panel rescue-panel${rescueActive ? ' active' : ''}`}><div className="rescue-icon">{rescueActive ? <CheckCircle2 size={21} /> : <Bolt size={21} fill="currentColor" />}</div><h2>{rescueActive ? 'Rescate en curso' : 'CUMPLE Rescate'}</h2><p>{rescueActive ? 'Estamos priorizando perfiles disponibles, cercanos y con alto índice CUMPLE.' : 'Encuentra reemplazos disponibles y con buen índice CUMPLE cuando un turno queda descubierto.'}</p><button className="primary-button" type="button" disabled={rescueActive} onClick={onRescue}><BriefcaseBusiness size={17} /> {rescueActive ? 'Búsqueda activada' : 'Activar rescate'}</button></article></section>
    <section className="operations-grid"><article className="panel shifts-panel"><div className="panel-heading table-heading"><div><h2>Próximos turnos</h2><p>Seguimiento rápido de cobertura y confirmaciones.</p></div><button className="text-button" type="button" onClick={() => onNavigate('Turnos')}>Gestionar turnos <ArrowUpRight size={14} /></button></div><div className="shift-table">{shifts.slice(0, 4).map((shift) => <ShiftRow key={shift.id} shift={shift} onSelect={() => onShift(shift.id)} />)}</div></article><aside className="panel talent-panel"><div className="panel-heading"><div><h2>Talento recomendado</h2><p>Disponible para tus turnos abiertos.</p></div><span className="ai-chip"><Sparkles size={12} /> Match IA</span></div><div className="worker-list">{workers.slice(0, 3).map((worker) => <WorkerCompact key={worker.id} worker={worker} onInvite={() => onToast(`Invitación enviada a ${worker.name}.`)} />)}</div><button className="full-secondary" type="button" onClick={() => onNavigate('Trabajadores')}><Users size={16} /> Explorar trabajadores</button></aside></section>
    <section className="bottom-grid"><article className="panel"><div className="panel-heading"><div><h2>Control de pagos</h2><p>Resumen estimado del periodo: {period.toLowerCase()}.</p></div><span className="safe-chip"><ShieldCheck size={13} /> Fondos protegidos</span></div><div className="payments-layout"><div className="payment-total"><span>Próximo desembolso</span><strong>S/ 1,840.00</strong><small>Viernes, 28 de agosto</small><div className="payment-progress"><i /></div><p><Check size={13} /> 76% de turnos validados</p></div><div className="payment-stats"><div><span><WalletCards size={16} /> Pagado este mes</span><strong>S/ 7,260</strong></div><div><span><TrendingUp size={16} /> Comisión de servicio</span><strong>S/ 806</strong></div><button type="button" onClick={() => onNavigate('Pagos')}>Revisar detalle <ArrowUpRight size={14} /></button></div></div></article><article className="panel"><div className="panel-heading"><div><h2>Actividad reciente</h2><p>Lo más importante de tu equipo.</p></div><button className="row-action" type="button" aria-label="Ver mensajes" onClick={() => onNavigate('Mensajes')}><MoreHorizontal size={18} /></button></div><div className="activity-list">{activity.map(({ icon: Icon, title, detail, tone }) => <div className="activity-item" key={title}><span className={`activity-icon ${tone}`}><Icon size={16} /></span><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div></article></section>
  </div>;
}

function ViewHeader({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) { return <section className="view-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><div className="view-header-actions">{children}</div></section>; }
function MetricCard({ label, value, trend, icon: Icon, gold = false }: { label: string; value: string; trend: string; icon: typeof CalendarDays; gold?: boolean }) { return <article className="metric-card"><div className="metric-top"><div className={`metric-icon${gold ? ' gold' : ''}`}><Icon size={19} /></div><span className="trend">{trend}</span></div><div className="metric-value">{value}</div><div className="metric-label">{label}</div></article>; }
function MiniStat({ label, value, detail, icon: Icon, warning = false }: { label: string; value: string; detail: string; icon: typeof CalendarDays; warning?: boolean }) { return <article className="mini-stat"><div className={`mini-stat-icon${warning ? ' warning' : ''}`}><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>; }

function ShiftRow({ shift, onSelect }: { shift: Shift; onSelect: () => void }) { return <button className="shift-row" role="row" type="button" onClick={onSelect}><span className="shift-role"><span className="role-icon"><BriefcaseBusiness size={17} /></span><span><strong>{shift.role}</strong><small>{shift.location} · {shift.schedule}</small></span></span><span className="staffing"><span className="avatar-stack">{Array.from({ length: Math.min(shift.confirmed, 3) }).map((_, index) => <i key={index}>{['AM', 'CR', 'LV'][index]}</i>)}</span><span><strong>{shift.confirmed}/{shift.required}</strong><small>confirmados</small></span></span><span><span className={`coverage-badge ${coverageClass(shift.coverage)}`}>{shift.coverage}</span></span><span className="row-pay"><strong>S/ {shift.pay}</strong><small>por persona</small></span><span className="row-action"><MoreHorizontal size={18} /></span></button>; }
function ManagedShift({ shift, selected, onSelect }: { shift: Shift; selected: boolean; onSelect: () => void }) { return <button className={`managed-shift${selected ? ' selected' : ''}`} type="button" onClick={onSelect}><span className="managed-date"><strong>{shift.date.split(',')[0]}</strong><small>{shift.date.includes(',') ? shift.date.split(',')[1] : 'Nuevo'}</small></span><span className="managed-copy"><strong>{shift.role}</strong><small><Clock3 size={13} /> {shift.schedule}<i /><MapPin size={13} /> {shift.location}</small></span><span className="managed-coverage"><span className={`coverage-badge ${coverageClass(shift.coverage)}`}>{shift.coverage}</span><small>{shift.confirmed}/{shift.required} confirmados</small></span><span className="managed-pay"><strong>S/ {shift.pay}</strong><small>por persona</small></span></button>; }
function WorkerCompact({ worker, onInvite }: { worker: Worker; onInvite: () => void }) { return <button className="worker-card" type="button" onClick={onInvite}><span className="worker-avatar">{worker.initials}<i /></span><span className="worker-info"><strong>{worker.name}</strong><small>{worker.role}</small><em>{worker.available}</em></span><span className="worker-match"><strong>{worker.match}%</strong><small>match</small></span></button>; }

function WorkerDirectoryCard({ worker, onMessage, onInvite }: { worker: Worker; onMessage: () => void; onInvite: () => void }) { return <article className="directory-card"><div className="directory-top"><span className="directory-avatar">{worker.initials}<i className={worker.status === 'Disponible' ? '' : 'away'} /></span><span className="match-ring"><strong>{worker.match}%</strong><small>match</small></span></div><div className="directory-identity"><h3>{worker.name} <BadgeCheck size={15} /></h3><p>{worker.role}</p><span className={`availability ${worker.status === 'Disponible' ? '' : 'muted'}`}>{worker.available}</span></div><div className="skill-row">{worker.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="worker-performance"><span><small>Índice CUMPLE</small><strong><Star size={13} fill="currentColor" /> {worker.score}</strong></span><span><small>Turnos realizados</small><strong>{worker.jobs}</strong></span></div><div className="directory-actions"><button className="secondary-button" type="button" onClick={onMessage}><MessageSquareText size={16} /> Mensaje</button><button className="primary-button" type="button" onClick={onInvite}><Send size={16} /> Invitar</button></div></article>; }

function TransactionRow({ transaction, onOpen }: { transaction: Transaction; onOpen: () => void }) { return <div className="transaction-row"><span className="transaction-name"><i className={transaction.status === 'Procesado' ? 'in' : ''}>{transaction.status === 'Procesado' ? <ArrowDownLeft size={16} /> : <Clock3 size={16} />}</i><span><strong>{transaction.description}</strong><small>{transaction.id} · {transaction.date}</small></span></span><span>{transaction.workers}</span><span><b className={`payment-status ${transaction.status.toLowerCase()}`}>{transaction.status}</b></span><span className="transaction-amount">S/ {transaction.amount.toLocaleString('es-PE')}</span><button className="row-action" type="button" aria-label={`Ver ${transaction.id}`} onClick={onOpen}><MoreHorizontal size={18} /></button></div>; }

function PublishModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-layer" role="presentation" onMouseDown={onClose}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="publish-title" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">Nuevo requerimiento</p><h2 id="publish-title">Publicar un turno</h2><p>Define lo esencial. Podrás editar los detalles después.</p></div><button className="icon-button" type="button" aria-label="Cerrar" onClick={onClose}><X size={18} /></button></div><form onSubmit={onSubmit}><label className="field full"><span>Rol requerido</span><input name="role" required placeholder="Ej. Mozo de salón" /></label><div className="form-grid"><label className="field"><span>Horario</span><input name="schedule" required placeholder="18:00 – 00:00" /></label><label className="field"><span>Sede o distrito</span><input name="location" required placeholder="Miraflores" /></label><label className="field"><span>Personas</span><input name="required" min="1" max="50" type="number" defaultValue="1" /></label><label className="field"><span>Pago por persona</span><div className="money-input"><span>S/</span><input name="pay" min="1" type="number" defaultValue="100" /></div></label></div><div className="form-note"><ShieldCheck size={17} /><span><strong>Publicación segura</strong> El pago se calcula y protege antes de confirmar trabajadores.</span></div><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancelar</button><button className="primary-button" type="submit"><Plus size={17} /> Publicar turno</button></div></form></section></div>; }
