FROM node:22-alpine
WORKDIR /workspace/apps/api
COPY apps/api/package*.json ./
RUN npm install --workspaces=false
COPY apps/api ./
EXPOSE 4000
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run dev"]
